import type { Metadata } from 'next';
import { ArrowRight, Radio, QrCode, Users, Clock3, Trophy, Lightbulb, Monitor, Download, PencilLine, UserPlus, Landmark, Globe2, MapPin, Compass, Rocket, Check } from 'lucide-react';
export const metadata: Metadata = { title: '서울 제퍼디 LIVE — 해치와 함께하는 서울 퀴즈쇼', description: 'QR코드 하나로 최대 10개 조가 함께 즐기는 실시간 서울 퀴즈쇼. 회원가입 없이 바로 시작하세요.' };
const cats=[{t:'서울 600년 역사',d:'한양도성부터 오늘의 서울까지',Icon:Landmark,c:'#91b8ff'},{t:'서울 행사 & 글로벌 이벤트',d:'축제와 국제 행사로 만나는 서울',Icon:Globe2,c:'#d4a8ff'},{t:'외국인 인기 서울 관광지 TOP5',d:'세계인이 사랑하는 서울의 명소',Icon:MapPin,c:'#7cddd0'},{t:'G3 서울플랜 5대 미래상',d:'서울이 그리는 다섯 가지 내일',Icon:Compass,c:'#ffd474'},{t:'미래 서울 & 도시전략',d:'더 나은 도시를 위한 전략과 비전',Icon:Rocket,c:'#ffa9b4'}];
const steps=[{n:'01',t:'진행자가 방을 만들어요',d:'참여 조 수만 고르면 끝. 6자리 입장코드와 QR코드가 바로 만들어집니다.',Icon:QrCode},{n:'02',t:'QR로 입장해요',d:'참가자는 QR을 스캔하고 조와 이름만 입력하면 준비 완료. 회원가입은 필요 없어요.',Icon:Users},{n:'03',t:'함께 풀고, 함께 웃어요',d:'문제판에서 문제를 고르면 50초 동안 모두가 동시에 도전합니다. 순위는 실시간으로!',Icon:Trophy}];
const features=[{t:'50초 동시 도전',d:'먼저 누른 사람만 답하는 방식이 아니라, 모든 참가자가 각자 한 번씩 답을 제출해요.',Icon:Clock3},{t:'글자 수 · 초성 힌트',d:'문제와 함께 힌트가 공개되어 누구나 부담 없이 참여할 수 있어요.',Icon:Lightbulb},{t:'조별 · 개인별 라이브 순위',d:'조 점수는 조원 평균이라 인원이 달라도 공정합니다. 동점은 공동 순위로 표시돼요.',Icon:Trophy},{t:'똑똑한 자동 채점',d:'동의어, 약칭, 영문·한글 표기, 축제·페스티벌까지 같은 뜻의 답을 인정합니다.',Icon:Check},{t:'큰 화면 모드',d:'빔프로젝터나 TV에 띄울 수 있는 전용 화면으로 현장 분위기를 살려 보세요.',Icon:Monitor},{t:'게임 중에도 입장 가능',d:'늦게 온 참가자도 같은 QR코드로 현재 문제의 남은 시간에 맞춰 바로 합류합니다.',Icon:UserPlus}];
const friends=[{src:'/haechi.jpg',n:'해치'},{src:'/jujak.jpg',n:'주작'},{src:'/baekho.jpg',n:'백호'},{src:'/cheongryong.jpg',n:'청룡'},{src:'/hyeonmu.jpg',n:'현무'}];
const faqs=[{q:'참가자도 회원가입을 해야 하나요?',a:'아니요. QR코드를 스캔하거나 6자리 입장코드를 입력한 뒤 조와 이름만 적으면 바로 참여할 수 있습니다.'},{q:'몇 명까지 함께할 수 있나요?',a:'1개 조부터 최대 10개 조까지 구성할 수 있고, 조 점수는 조원 평균으로 계산되어 조별 인원이 달라도 괜찮습니다.'},{q:'게임 도중에 브라우저를 닫으면 어떻게 되나요?',a:'참가자와 진행자의 재접속 권한은 같은 브라우저에 저장됩니다. 방 링크로 다시 들어오면 이어서 참여할 수 있어요.'},{q:'자동 채점이 틀렸다면요?',a:'진행자가 정답 공개 후 제출된 답안을 확인하고 정답 인정 여부를 직접 수정할 수 있습니다.'},{q:'게임 결과를 보관할 수 있나요?',a:'게임 종료 후 진행자는 조, 이름, 문제번호, 제출 답안, 점수가 담긴 전체 응답 결과를 CSV 파일로 내려받을 수 있습니다.'}];
export default function Landing(){
 return <div className="site lp"><header className="header"><a href="/landing" className="brand"><img className="brand-haechi" src="/haechi.jpg" alt="해치"/><span>서울 제퍼디 <b>LIVE</b></span></a><div className="header-right"><nav className="lp-nav" aria-label="페이지 내 이동"><a href="#how">진행 방법</a><a href="#categories">문제 분야</a><a href="#features">특징</a><a href="#faq">자주 묻는 질문</a></nav><a className="primary" href="/">시작하기<ArrowRight size={16}/></a></div></header>
 <main>
 <section className="lp-hero"><div className="lp-hero-text"><span className="tag"><Radio size={14}/> 실시간 온라인 퀴즈쇼</span><h1>서울을 아는 우리,<br/><span>함께 풀면 더 재밌다.</span></h1><p className="intro">해치와 함께하는 서울 퀴즈쇼, 서울 제퍼디 LIVE. QR코드 하나로 최대 10개 조가 동시에 도전하고, 순위는 실시간으로 공개됩니다.</p><div className="lp-cta"><a className="primary" href="/">퀴즈쇼 입장하기<ArrowRight size={18}/></a><a className="secondary" href="#how">어떻게 진행되나요?</a></div><ul className="lp-stats"><li><b>5</b><span>개 분야</span></li><li><b>25</b><span>문제</span></li><li><b>50</b><span>초 도전</span></li><li><b>10</b><span>개 조까지</span></li></ul></div><div className="lp-hero-visual"><img className="lp-hero-night" src="/seoul-night.png" alt="AI로 생성한 한강과 서울타워의 빛나는 서울 야경"/><div className="lp-hero-caption"><span>우리가 함께 알아갈 도시</span><b>SEOUL, MY SOUL</b></div><img className="lp-hero-friends" src="/friends.png" alt="해치와 소울프렌즈 백호 주작 청룡 현무"/></div></section>
 <section className="lp-section" id="how"><div className="lp-heading"><div className="eyebrow">HOW IT WORKS</div><h2>3단계면 퀴즈쇼가 시작됩니다</h2><p>설치도, 회원가입도 필요 없어요. 링크 하나로 모두 연결됩니다.</p></div><ol className="lp-steps">{steps.map(({n,t,d,Icon})=><li key={n}><div className="lp-step-top"><span>{n}</span><Icon size={22}/></div><h3>{t}</h3><p>{d}</p></li>)}</ol></section>
 <section className="lp-section" id="categories"><div className="lp-heading"><div className="eyebrow">TODAY&apos;S BOARD</div><h2>5개 분야, 25문제로 만나는 서울</h2><p>100점부터 500점까지, 분야별로 난이도가 올라갑니다.</p></div><div className="lp-cats">{cats.map(({t,d,Icon,c})=><div className="lp-cat" key={t} style={{'--category-color':c} as React.CSSProperties}><Icon size={24}/><h3>{t}</h3><p>{d}</p><div className="lp-points">{[100,200,300,400,500].map(p=><span key={p}>{p}</span>)}</div></div>)}</div></section>
 <section className="lp-section" id="features"><div className="lp-heading"><div className="eyebrow">FEATURES</div><h2>모두가 주인공이 되는 퀴즈쇼</h2><p>빠른 사람만 즐거운 퀴즈가 아니라, 모든 참가자가 끝까지 함께합니다.</p></div><div className="lp-features">{features.map(({t,d,Icon})=><div className="lp-feature" key={t}><span className="mini-icon"><Icon size={21}/></span><h3>{t}</h3><p>{d}</p></div>)}</div></section>
 <section className="lp-section lp-host"><div className="lp-host-text"><div className="eyebrow">FOR HOSTS</div><h2>진행자는 진행에만 집중하세요</h2><p>채점과 집계는 서울 제퍼디 LIVE가 맡습니다.</p><ul><li><PencilLine size={18}/><div><b>답안 확인 · 채점 수정</b><span>정답 공개 후 같은 뜻의 답을 직접 정답으로 인정할 수 있어요.</span></div></li><li><Monitor size={18}/><div><b>큰 화면 · 참여 QR 상시 표시</b><span>진행 중에도 QR코드가 화면에 남아 있어 언제든 새 참가자를 받을 수 있어요.</span></div></li><li><Download size={18}/><div><b>전체 응답 결과 CSV 다운로드</b><span>조, 이름, 문제별 답안과 점수를 한 번에 내려받아 보관하세요.</span></div></li></ul><a className="primary" href="/">새 게임방 만들기<ArrowRight size={18}/></a></div><div className="lp-friends">{friends.map(f=><figure key={f.n}><img src={f.src} alt={f.n}/><figcaption>{f.n}</figcaption></figure>)}<p>해치와 소울프렌즈가 각 조의 마스코트로 함께합니다.</p></div></section>
 <section className="lp-section" id="faq"><div className="lp-heading"><div className="eyebrow">FAQ</div><h2>자주 묻는 질문</h2></div><div className="lp-faq">{faqs.map(f=><details key={f.q}><summary>{f.q}</summary><p>{f.a}</p></details>)}</div></section>
 <section className="lp-final"><img src="/haechi.jpg" alt="반갑게 손을 흔드는 해치"/><div><h2>모이면, 시작합니다.</h2><p>지금 방을 만들고 참여 링크를 공유해 보세요.</p></div><a className="primary" href="/">지금 시작하기<ArrowRight size={18}/></a></section>
 </main>
 <footer><span>SEOUL JEOPARDY LIVE</span><span>해치와 함께 서울을 알아가는 즐거운 시간</span></footer></div>;
}
